### PR TITLE
SEO optimization and usage of CSS

### PR DESCRIPTION
**Pull request by mstomar698**
for Issue #2

- [x] added meta tags 
- [x] removed inline CSS as many as I can
- [x] removed unused font families from assets
- [x] changed .png image to .svg image

### CODE REVIEW

**Comment by mstomar698** [comment]
review it and do tell what else can I improve here!?

**Comment by 1stdevfriend** [comment]
It's under review. Will let you know as the first thing in office mondays

**Comment by mstomar698** [comment]
Are there any changes required in this PR.
please review it it is being on hold for kore then a week.

**Comment by 1stdevfriend** [comment]
Great! Feel free to apply at info@koders.in if you're looking for jobs at an SDE intern

**Pull request merged**
